language: node_js
node_js: node
cache:
  directories:
  - node_modules
after_success:
- npm run build
- "./.travis-deploy.sh"
env:
  global:
    secure: eVlAE9y1Yyo095MiYVzmp1HuxwnqPgbJnJ042I11DVQk1rvweyOASZtBVaQjWk6O1Ar98C+ULovu9zG5BhlEvmFmKReUKdoxFNiLTX3CqpaBfV1OQRPeiaKgdohvtoffkiWNclwTtZKT7oCBEPDbNBLzs3p8SZjoPbVeq+1S6vTeeYVwJ9JzZKYBGmZWxDOS4LHqdNEMxyJ7q2fCFuk0uwPPTlLtVaq+n1mAhS/xhIgd7FzG7mH1YF1fvfUaPaZNU6xaGa6ovANqrYcjbGTX/g5hxvWKdyQVUAc5UDgOXrfTxO8duy68CErXUkoPZS9TjnhTCRn8xTNNMCrMUae5Qfucay+jJyXpDMcGPdu94XUo4IvzxTB+Y0vf7zbhrSnXVqWlfCoyD1zoWR8C5uMJyDhJnHiFYLscmq8kL+MC4FBh0qDEsyTknjG7OAaObTxRo8iclq+6aRIJTYhh0cIRf57nHJmxl1Qx4jfyeW2l3xPSkddaMxzVnSbxwjuoo10NaFSnBSK/yDSKtLov4oyhVD/2FdcyN4LV8eWQeyhsFtDAYwPqMyGMytETobqqpT1Bg6c93UR26IH2P+3CUaq1fKeLbPCHP7gCTomJ+ShM/0STo6PwYqmoPYTPnDy8rC6q4deLrtEHVNfwToXRtTSzOjXU0G/zhK3hV8UzqpBFtfk=
