export const SIGNIN_IN_PROGRESS = 'SIGNIN_IN_PROGRESS';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_FAILURE = 'SIGNIN_FAILURE';

export const SIGNUP_IN_PROGRESS = 'SIGNUP_IN_PROGRESS';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const DISPLAY_WAITINGBOX = 'DISPLAY_WAITINGBOX';
export const HIDE_WAITINGBOX = 'HIDE_WAITINGBOX';


export const UPDATE_CAT_ID = 'UPDATE_CAT_ID';
export const UPDATE_CAT_NAME = 'UPDATE_CAT_NAME';
